package View;

import java.awt.Color;
import java.awt.Font;
import Model.Project;
import Controller.ProjectController;
import javax.swing.DefaultListModel;

/**
 *
 * @author marcelo
 */
public class MainStream extends javax.swing.JFrame {


    private Project project;
    private ProjectController projectController;
    private DefaultListModel<Project> defaultListModel;
    
    public MainStream() {
        
        initComponents();
        decorateTableTasks();
        initDataController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Toolbar = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SubTitle = new javax.swing.JLabel();
        PanelProject = new javax.swing.JPanel();
        ProjectTitle = new javax.swing.JLabel();
        PanelTask = new javax.swing.JPanel();
        TaskTitle = new javax.swing.JLabel();
        PanelProjectList = new javax.swing.JPanel();
        jScrollPanelProjects = new javax.swing.JScrollPane();
        ListProjects = new javax.swing.JList<>();
        GridTask = new javax.swing.JPanel();
        EmptyList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTasks = new javax.swing.JTable();
        AddTask = new javax.swing.JButton();
        AddProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(700, 600));

        Toolbar.setBackground(new java.awt.Color(255, 0, 0));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Projetos e Tarefas");

        SubTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SubTitle.setForeground(new java.awt.Color(255, 255, 255));
        SubTitle.setText("Notações");

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                    .addComponent(SubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ToolbarLayout.setVerticalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelProject.setBackground(new java.awt.Color(255, 255, 255));
        PanelProject.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProjectTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProjectTitle.setForeground(new java.awt.Color(255, 0, 0));
        ProjectTitle.setText("Projetos");

        javax.swing.GroupLayout PanelProjectLayout = new javax.swing.GroupLayout(PanelProject);
        PanelProject.setLayout(PanelProjectLayout);
        PanelProjectLayout.setHorizontalGroup(
            PanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        PanelProjectLayout.setVerticalGroup(
            PanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelTask.setBackground(new java.awt.Color(255, 255, 255));
        PanelTask.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TaskTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TaskTitle.setForeground(new java.awt.Color(255, 0, 0));
        TaskTitle.setText("Tarefas");

        javax.swing.GroupLayout PanelTaskLayout = new javax.swing.GroupLayout(PanelTask);
        PanelTask.setLayout(PanelTaskLayout);
        PanelTaskLayout.setHorizontalGroup(
            PanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTaskLayout.setVerticalGroup(
            PanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelProjectList.setBackground(new java.awt.Color(255, 255, 255));
        PanelProjectList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListProjects.setBackground(new java.awt.Color(255, 255, 255));
        ListProjects.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListProjects.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPanelProjects.setViewportView(ListProjects);

        javax.swing.GroupLayout PanelProjectListLayout = new javax.swing.GroupLayout(PanelProjectList);
        PanelProjectList.setLayout(PanelProjectListLayout);
        PanelProjectListLayout.setHorizontalGroup(
            PanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelProjectListLayout.setVerticalGroup(
            PanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanelProjects)
                .addContainerGap())
        );

        GridTask.setBackground(new java.awt.Color(255, 255, 255));
        GridTask.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EmptyList.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EmptyListLayout = new javax.swing.GroupLayout(EmptyList);
        EmptyList.setLayout(EmptyListLayout);
        EmptyListLayout.setHorizontalGroup(
            EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EmptyListLayout.setVerticalGroup(
            EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TableTasks.setBackground(new java.awt.Color(255, 255, 255));
        TableTasks.setForeground(new java.awt.Color(102, 102, 102));
        TableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableTasks);

        javax.swing.GroupLayout GridTaskLayout = new javax.swing.GroupLayout(GridTask);
        GridTask.setLayout(GridTaskLayout);
        GridTaskLayout.setHorizontalGroup(
            GridTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GridTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GridTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(EmptyList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        GridTaskLayout.setVerticalGroup(
            GridTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GridTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmptyList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        AddTask.setBackground(new java.awt.Color(204, 204, 204));
        AddTask.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AddTask.setForeground(new java.awt.Color(255, 0, 0));
        AddTask.setText("+");
        AddTask.setAlignmentY(0.0F);
        AddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskActionPerformed(evt);
            }
        });

        AddProject.setBackground(new java.awt.Color(204, 204, 204));
        AddProject.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AddProject.setForeground(new java.awt.Color(255, 0, 0));
        AddProject.setText("+");
        AddProject.setAlignmentY(0.0F);
        AddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddProject))
                    .addComponent(PanelProjectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GridTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddProject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(GridTask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTaskActionPerformed

    private void AddProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProjectActionPerformed
    
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
    }//GEN-LAST:event_AddProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainStream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainStream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainStream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainStream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainStream().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProject;
    private javax.swing.JButton AddTask;
    private javax.swing.JPanel EmptyList;
    private javax.swing.JPanel GridTask;
    private javax.swing.JList<String> ListProjects;
    private javax.swing.JPanel PanelProject;
    private javax.swing.JPanel PanelProjectList;
    private javax.swing.JPanel PanelTask;
    private javax.swing.JLabel ProjectTitle;
    private javax.swing.JLabel SubTitle;
    private javax.swing.JTable TableTasks;
    private javax.swing.JLabel TaskTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanelProjects;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTasks(){
        
        TableTasks.getTableHeader().setFont(new Font("Segor UI", Font.BOLD, 14));
        TableTasks.getTableHeader().setBackground(new Color(255,255,255));
        TableTasks.getTableHeader().setForeground(Color.red);
        TableTasks.getAutoCreateRowSorter();
    }
    
    public void initDataController(){
        
        projectController = new ProjectController();
        project = new Project();
        
        project.getId();
        project.getName();
        project.getDescription();
        
        
    }
}
