/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CApp;

import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) {
        
        JOptionPane.showMessageDialog(null, "Hello Girls!");
    }

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
